server:
  port: ${PORT:8081}

spring:
  application:
    name: ${NAME:config-server}
  
eureka:
  instance:
    instance-id: ${spring.application.name}-${SEQUENCE_NO}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoint:
    shutdown:
      enabled:  true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - "*"
