server:
  port: 8100
logging:
    config: http://sms.sistemastg.com/sms-logback.xml
spring:
  application:
    name: ${NAME:sms-server}
    
global:
  name: eduardo
  folder: uno

management:
  endpoint:
    shutdown:
      enabled:  true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - "*"
