server:
  port: 8100
logging:
    config: http://sms.sistemastg.com/sms-logback.xml
spring:
  application:
    name: ${NAME:sms-server}
  profiles:
    active: dev
    
---
spring:
  profiles: dev
global:
  name: sempere
  folder: sem
  
---
global:
  name: 222s
  folder: wwwdsdsds
    

