server:
  port: 8100
logging:
    config: http://sms.sistemastg.com/sms-logback.xml
spring:
  application:
    name: ${NAME:sms-server}
  profiles:
    active: "dev"
    
global:
  name: sempere
  folder: sem
  
---
spring:
  config:
    activate:
      on-profile: "dev"
global:
  name: MAyra
  folder: aaaa
